import { Theme } from "../index.types";

export type ThemeKeys =
  | "a11y-dark"
  | "atom-dark"
  | "cb"
  | "coldark-dark"
  | "darcula"
  | "dracula"
  | "duotone-dark"
  | "duotone-earth"
  | "duotone-forest"
  | "duotone-sea"
  | "duotone-space"
  | "gruvbox-dark"
  | "hopscotch"
  | "laserwave"
  | "lucario"
  | "material-dark"
  | "material-oceanic"
  | "night-owl"
  | "nord"
  | "one-dark"
  | "shades-of-purple"
  | "solarized-dark-atom"
  | "synthwave84"
  | "vsc-dark-plus"
  | "xonokai"
  | "z-touch"
  | "base16-ateliersulphurpool-light"
  | "coldark-cold"
  | "coy-without-shadows"
  | "duotone-light"
  | "ghcolors"
  | "gruvbox-light"
  | "holi-theme"
  | "material-light"
  | "one-light"
  | "pojoaque"
  | "vs";

export const PrismThemes: Record<ThemeKeys, Theme> = {
  // Dark Themes
  "a11y-dark": {
    border: "1px solid #2b2b2b",
    backgroundColor: "#2b2b2b",
    color: "#f8f8f2",
    numbersBackgroundColor: "#2b2b2b",
    numbersColor: "#d4d0ab",
    numbersBorder: "1px solid #2b2b2b",
    caretColor: "#ffa07a",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "atom-dark": {
    border: "1px solid #1d1f21",
    backgroundColor: "#1d1f21",
    color: "#c5c8c6",
    numbersBackgroundColor: "#1d1f21",
    numbersColor: "#7c7c7c",
    numbersBorder: "1px solid #1d1f21",
    caretColor: "#528bff",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  cb: {
    border: "1px solid #222",
    backgroundColor: "#222",
    color: "#fff",
    numbersBackgroundColor: "#222",
    numbersColor: "#888",
    numbersBorder: "1px solid #222",
    caretColor: "#f8f8f2",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "coldark-dark": {
    border: "1px solid #111b27",
    backgroundColor: "#111b27",
    color: "#e3eaf2",
    numbersBackgroundColor: "#111b27",
    numbersColor: "#8da1b9",
    numbersBorder: "1px solid #111b27",
    caretColor: "#66cccc",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  darcula: {
    border: "1px solid #2b2b2b",
    backgroundColor: "#2b2b2b",
    color: "#a9b7c6",
    numbersBackgroundColor: "#2b2b2b",
    numbersColor: "#606366",
    numbersBorder: "1px solid #2b2b2b",
    caretColor: "#a9b7c6",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  dracula: {
    border: "1px solid #282a36",
    backgroundColor: "#282a36",
    color: "#f8f8f2",
    numbersBackgroundColor: "#282a36",
    numbersColor: "#6272a4",
    numbersBorder: "1px solid #282a36",
    caretColor: "#f8f8f2",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "duotone-dark": {
    border: "1px solid #2a2734",
    backgroundColor: "#2a2734",
    color: "#9a86fd",
    numbersBackgroundColor: "#2a2734",
    numbersColor: "#6c6783",
    numbersBorder: "1px solid #2a2734",
    caretColor: "#ffad5c",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "duotone-earth": {
    border: "1px solid #322d29",
    backgroundColor: "#322d29",
    color: "#88786d",
    numbersBackgroundColor: "#322d29",
    numbersColor: "#6a5f58",
    numbersBorder: "1px solid #322d29",
    caretColor: "#e5c07b",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "duotone-forest": {
    border: "1px solid #2a2d2a",
    backgroundColor: "#2a2d2a",
    color: "#687d68",
    numbersBackgroundColor: "#2a2d2a",
    numbersColor: "#535f53",
    numbersBorder: "1px solid #2a2d2a",
    caretColor: "#a2b34d",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "duotone-sea": {
    border: "1px solid #1d262f",
    backgroundColor: "#1d262f",
    color: "#57718e",
    numbersBackgroundColor: "#1d262f",
    numbersColor: "#4a5f78",
    numbersBorder: "1px solid #1d262f",
    caretColor: "#7eb6f6",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "duotone-space": {
    border: "1px solid #24242e",
    backgroundColor: "#24242e",
    color: "#767693",
    numbersBackgroundColor: "#24242e",
    numbersColor: "#5b5b76",
    numbersBorder: "1px solid #24242e",
    caretColor: "#fe8c52",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "gruvbox-dark": {
    border: "1px solid #1d2021",
    backgroundColor: "#1d2021",
    color: "#ebdbb2",
    numbersBackgroundColor: "#1d2021",
    numbersColor: "#7c6f64",
    numbersBorder: "1px solid #1d2021",
    caretColor: "#fe8019",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  hopscotch: {
    border: "1px solid #322931",
    backgroundColor: "#322931",
    color: "#b9b5b8",
    numbersBackgroundColor: "#322931",
    numbersColor: "#797379",
    numbersBorder: "1px solid #322931",
    caretColor: "#fd8b19",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  laserwave: {
    border: "1px solid #27212e",
    backgroundColor: "#27212e",
    color: "#ffffff",
    numbersBackgroundColor: "#27212e",
    numbersColor: "#91889b",
    numbersBorder: "1px solid #27212e",
    caretColor: "#fe4450",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  lucario: {
    border: "1px solid #2b3e50",
    backgroundColor: "#2b3e50",
    color: "#f8f8f2",
    numbersBackgroundColor: "#2b3e50",
    numbersColor: "#5c98cd",
    numbersBorder: "1px solid #2b3e50",
    caretColor: "#f8f8f2",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "material-dark": {
    border: "1px solid #2f2f2f",
    backgroundColor: "#2f2f2f",
    color: "#eeffff",
    numbersBackgroundColor: "#2f2f2f",
    numbersColor: "#616161",
    numbersBorder: "1px solid #2f2f2f",
    caretColor: "#89ddff",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "material-oceanic": {
    border: "1px solid #263238",
    backgroundColor: "#263238",
    color: "#c3cee3",
    numbersBackgroundColor: "#263238",
    numbersColor: "#546e7a",
    numbersBorder: "1px solid #263238",
    caretColor: "#89ddff",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "night-owl": {
    border: "1px solid #011627",
    backgroundColor: "#011627",
    color: "#d6deeb",
    numbersBackgroundColor: "#011627",
    numbersColor: "#7fdbca",
    numbersBorder: "1px solid #011627",
    caretColor: "#80a4c2",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  nord: {
    border: "1px solid #2e3440",
    backgroundColor: "#2e3440",
    color: "#d8dee9",
    numbersBackgroundColor: "#2e3440",
    numbersColor: "#4c566a",
    numbersBorder: "1px solid #2e3440",
    caretColor: "#88c0d0",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "one-dark": {
    border: "1px solid #282c34",
    backgroundColor: "#282c34",
    color: "#abb2bf",
    numbersBackgroundColor: "#282c34",
    numbersColor: "#4b5263",
    numbersBorder: "1px solid #282c34",
    caretColor: "#528bff",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "shades-of-purple": {
    border: "1px solid #2d2b55",
    backgroundColor: "#2d2b55",
    color: "#e3dfff",
    numbersBackgroundColor: "#2d2b55",
    numbersColor: "#a599e9",
    numbersBorder: "1px solid #2d2b55",
    caretColor: "#fad000",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "solarized-dark-atom": {
    border: "1px solid #002b36",
    backgroundColor: "#002b36",
    color: "#839496",
    numbersBackgroundColor: "#002b36",
    numbersColor: "#586e75",
    numbersBorder: "1px solid #002b36",
    caretColor: "#d33682",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  synthwave84: {
    border: "1px solid #2b213a",
    backgroundColor: "#2b213a",
    color: "#f92aad",
    numbersBackgroundColor: "#2b213a",
    numbersColor: "#495495",
    numbersBorder: "1px solid #2b213a",
    caretColor: "#36f9f6",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "vsc-dark-plus": {
    border: "1px solid #1e1e1e",
    backgroundColor: "#1e1e1e",
    color: "#d4d4d4",
    numbersBackgroundColor: "#1e1e1e",
    numbersColor: "#858585",
    numbersBorder: "1px solid #1e1e1e",
    caretColor: "#d7ba7d",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  xonokai: {
    border: "1px solid #2a2a2a",
    backgroundColor: "#2a2a2a",
    color: "#f8f8f2",
    numbersBackgroundColor: "#2a2a2a",
    numbersColor: "#7e7e7e",
    numbersBorder: "1px solid #2a2a2a",
    caretColor: "#f92672",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "z-touch": {
    border: "1px solid #0a0a0a",
    backgroundColor: "#0a0a0a",
    color: "#fff",
    numbersBackgroundColor: "#0a0a0a",
    numbersColor: "#747474",
    numbersBorder: "1px solid #0a0a0a",
    caretColor: "#fff",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  // Light Themes
  "base16-ateliersulphurpool-light": {
    border: "1px solid #f5f7ff",
    backgroundColor: "#f5f7ff",
    color: "#5e6687",
    numbersBackgroundColor: "#f5f7ff",
    numbersColor: "#898ea4",
    numbersBorder: "1px solid #f5f7ff",
    caretColor: "#3d8fd1",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "coldark-cold": {
    border: "1px solid #e3eaf2",
    backgroundColor: "#e3eaf2",
    color: "#111b27",
    numbersBackgroundColor: "#e3eaf2",
    numbersColor: "#8da1b9",
    numbersBorder: "1px solid #e3eaf2",
    caretColor: "#007474",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "coy-without-shadows": {
    border: "1px solid #fff",
    backgroundColor: "#fff",
    color: "#000",
    numbersBackgroundColor: "#fff",
    numbersColor: "#999",
    numbersBorder: "1px solid #fff",
    caretColor: "#000",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "duotone-light": {
    border: "1px solid #faf8f5",
    backgroundColor: "#faf8f5",
    color: "#b29762",
    numbersBackgroundColor: "#faf8f5",
    numbersColor: "#cdc4b1",
    numbersBorder: "1px solid #faf8f5",
    caretColor: "#063289",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  ghcolors: {
    border: "1px solid #fff",
    backgroundColor: "#fff",
    color: "#393A34",
    numbersBackgroundColor: "#fff",
    numbersColor: "#a0a1a7",
    numbersBorder: "1px solid #fff",
    caretColor: "#9a050f",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "gruvbox-light": {
    border: "1px solid #fbf1c7",
    backgroundColor: "#fbf1c7",
    color: "#3c3836",
    numbersBackgroundColor: "#fbf1c7",
    numbersColor: "#9d8374",
    numbersBorder: "1px solid #fbf1c7",
    caretColor: "#af3a03",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "holi-theme": {
    border: "1px solid #fff",
    backgroundColor: "#fff",
    color: "#4a4a4a",
    numbersBackgroundColor: "#fff",
    numbersColor: "#c7c7c7",
    numbersBorder: "1px solid #fff",
    caretColor: "#f65f91",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "material-light": {
    border: "1px solid #fafafa",
    backgroundColor: "#fafafa",
    color: "#90a4ae",
    numbersBackgroundColor: "#fafafa",
    numbersColor: "#cfd8dc",
    numbersBorder: "1px solid #fafafa",
    caretColor: "#39adb5",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  "one-light": {
    border: "1px solid #fafafa",
    backgroundColor: "#fafafa",
    color: "#383a42",
    numbersBackgroundColor: "#fafafa",
    numbersColor: "#a0a1a7",
    numbersBorder: "1px solid #fafafa",
    caretColor: "#526fff",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  pojoaque: {
    border: "1px solid #181914",
    backgroundColor: "#181914",
    color: "#dccf8f",
    numbersBackgroundColor: "#181914",
    numbersColor: "#7a7a5a",
    numbersBorder: "1px solid #181914",
    caretColor: "#b3a832",
    font: "jetbrainsmono",
    fontSize: 14,
  },
  vs: {
    border: "1px solid #fff",
    backgroundColor: "#fff",
    color: "#000",
    numbersBackgroundColor: "#fff",
    numbersColor: "#a5a5a5",
    numbersBorder: "1px solid #fff",
    caretColor: "#000",
    font: "jetbrainsmono",
    fontSize: 14,
  },
};
